version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - WouterVdS
  labels:
  - dependency update
  ignore:
  - dependency-name: faker
    versions:
    - 6.6.2
    - 6.6.3
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
