language: python
dist: xenial
python:
  - "3.6"
env:
  global:
    - BUILD_ON_TRAVIS=true
addons:
  sonarcloud:
    organization: "woutervds-github"
install:
  - pip install -r requirements.txt
  - cp templateSecrets.yml secrets.yml
  - python manage.py makemigrations
script:
  - coverage run manage.py test
  - coverage xml -i
  - sonar-scanner