language: python
python:
  - "3.6"
env:
  global:
    - BUILD_ON_TRAVIS=true
install:
  - pip install -r requirements.txt
  - cp templateSecrets.yml secrets.yml
  - python manage.py makemigrations
script:
  - python manage.py test