language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
cache: pip
env:
  global:
    - BUILD_ON_TRAVIS=true
notifications:
  email: false
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - cp templateSecrets.yml secrets.yml
  - python manage.py makemigrations
script:
  - coverage run --omit="*/virtualenv*,BosvogelWebPlatform/wsgi.py" manage.py test
after_success:
  - coveralls
