language: python
dist: xenial
python:
  - "3.6"
env:
  global:
    - BUILD_ON_TRAVIS=true
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - cp templateSecrets.yml secrets.yml
  - python manage.py makemigrations
script:
  - python manage.py test
  - coverage run --omit="*/virtualenv*" --branch manage.py test
after_success:
  - coveralls