language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
cache: pip
env:
  global:
    - DEBUG=False
notifications:
  email: false
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - python manage.py makemigrations
script:
  - coverage run manage.py test
after_success:
  - coveralls
