"""
Django settings for BosvogelWebPlatform project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import logging.config
import os

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# Environment Variables, these need to be changed in the production environment!
DEFAULT_DEBUG = True

env = environ.Env()
DEBUG = env('DEBUG', default=DEFAULT_DEBUG)
PRODUCTION_ENVIRONMENT = env('PRODUCTION_ENVIRONMENT', default=False)
SECRET_KEY = env('SECRET_KEY', default='*1ev7j$pn*he&0tn8o^12)tbi!e(h4w4^cxu8v(5*48z1syo-!')
if not DEBUG and SECRET_KEY == '*1ev7j$pn*he&0tn8o^12)tbi!e(h4w4^cxu8v(5*48z1syo-!':  # pragma: no cover
    raise ImproperlyConfigured('Add the SECRET_KEY environment variable to overwrite the default one in production!')
ALLOWED_HOSTS = env('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])
MEDIA_ROOT = env('MEDIA_ROOT', default=os.path.join(BASE_DIR, 'dev-media-root'))
MEDIA_URL = env('MEDIA_URL', default='/media/')
STATIC_ROOT = env('STATIC_ROOT', default='dev-static-root')
STATIC_URL = env('STATIC_URL', default='/static/')

# Email
EMAIL_CONFIG = env.email_url(
    'EMAIL_URL', default='consolemail://')
vars().update(EMAIL_CONFIG)

EMAIL_ADDRESS_RENT = env('RENTAL_MAIL_ADDRESS', default='verhuur@bosvogels.be')
EMAIL_ADDRESS_NOREPLY = env('RENTAL_MAIL_ADDRESS', default='noreply@bosvogels.be')

# Production Checks
if PRODUCTION_ENVIRONMENT:  # pragma: no cover
    if SECRET_KEY == '*1ev7j$pn*he&0tn8o^12)tbi!e(h4w4^cxu8v(5*48z1syo-!':
        raise ImproperlyConfigured('Add the SECRET_KEY environment variable to overwrite the default in production!')
    if EMAIL_CONFIG['EMAIL_BACKEND'] == 'django.core.mail.backends.console.EmailBackend':
        raise ImproperlyConfigured('Email still configured as console mail, add configuration to environment!')
    if ALLOWED_HOSTS == ['localhost', '127.0.0.1']:
        raise ImproperlyConfigured('Add the correct hostname to the ALLOWED_HOSTS environment variable!')
    if MEDIA_ROOT == os.path.join(BASE_DIR, 'dev-media-root'):
        raise ImproperlyConfigured('Set the MEDIA_ROOT environment variable to the correct value!')


MEDIA_URL = '/media/'

# Application definition
INSTALLED_APPS = [
    'apps.home',
    'apps.profile',
    'apps.place',
    'apps.agenda',
    'apps.rent',
    'apps.takken',
    'rules.apps.AutodiscoverRulesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Required for Django-Rules
AUTHENTICATION_BACKENDS = (
    'rules.permissions.ObjectPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',
)

ROOT_URLCONF = 'BosvogelWebPlatform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BosvogelWebPlatform.wsgi.application'

INTERNAL_IPS = ['127.0.0.1']

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'nl-BE'
TIME_ZONE = 'CET'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# Django Debug Toolbar
# Fix for this problem: https://github.com/jazzband/django-debug-toolbar/issues/1035
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK':
        lambda r:
            r.environ.get('SERVER_NAME', None) != 'testserver'and (r.META.get('REMOTE_ADDR', None) in INTERNAL_IPS)
}
